sudo: required
dist: trusty
language: node_js
node_js:
  - '4.2'

addons:
# From some tests it seems you can only have one firefox addon.
# Adding two results in the last one defined being the one installed.
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install

script: npm test
